---
application:
  name: "testa"
  project: "new"
  organization: "QoveryCommunity"
databases:
- type: "REDIS"
  name: "db"
  version: "6"
- type: "POSTGRESQL"
  name: "db"
  version: "11"
routers:
- name: "main-testa"
  routes:
  - application_name: "testa"
    paths:
    - "/*"
